##Variables and Assignment Statements

In [1]:
4+72

76

In [6]:
x=7

In [7]:
y=3

##Adding Variable Values and Viewing the Result

In [8]:
x+y

10

In [9]:
total = x+y
total

10

##Type

In [10]:
type(x)

int

In [11]:
type(10.5)

float

##Arithmetic
* Multiplication (*)

In [12]:
7*4

28

* Exponentiation (**)

In [13]:
2**10

1024

* True Division (/) vs. Floor Division (//)

True Division (/)

In [14]:
7/4

1.75

Floor Division (//)

In [15]:
7//4

1

In [16]:
3//5

0

In [17]:
14//7

2

In [18]:
# in true division
-13/4

-3.25

In [19]:
# in floor division
-13//4

-4

* Remainder Operator (%)

In [20]:
17%5

2

In [21]:
7.5%3.5

0.5

* Grouping Expressions with Parentheses

In [22]:
10*(5+3)

80

In [23]:
10*5+3

53

##Function print and an Intro to Single and double quoted Strings

In [24]:
print('Welcome to Python!')

Welcome to Python!


In [25]:
print("Welcome to Python!")

Welcome to Python!


##Printing a comma-separated list of items

In [26]:
print('Welcome','to','Python!')

Welcome to Python!


##Including Quotes in String

In [27]:
print('Display "hi" in quotes')

Display "hi" in quotes


In [28]:
print('Display 'hi' in quotes')

SyntaxError: invalid syntax (Temp/ipykernel_9688/102489360.py, line 1)

In [29]:
print('Display \'hi\' in quotes')

Display 'hi' in quotes


##Getting Input from the User

In [32]:
name = input("What's your name? ")
name

'Paul'

In [33]:
print(name)

Paul


## Function input always return a string

In [34]:
value1 = input('Enter first number: ')
value1

'7'

In [35]:
value2 = input('Enter second number: ')
value2

'3'

In [36]:
value1+value2

'73'

In [38]:
value = input('Enter an integer: ')
value = int(value)
value

7

In [39]:
another_value = input('Enter another value: ')
another_value = int(another_value)
another_value

13

In [40]:
value+another_value

20

In [41]:
bad_value = int(input('Enter another integer: '))
bad_value

ValueError: invalid literal for int() with base 10: 'hello'

In [42]:
int(10.5)

10

##Decision making: the if statement and comparison operators

In [43]:
7>4

True

In [44]:
7<4

False

In [46]:
7> =4

SyntaxError: invalid syntax (Temp/ipykernel_9688/3972611547.py, line 1)

##Making Decisions with the if statement: introducing scripts

In [48]:
print('Enter two integers, and I will tell you',
      'the relationships they satisfy.')

Enter two integers, and I will tell you the relationships they satisfy.


In [50]:
#read first integer
number1 = int(input('Enter first integer: '))
number1

37

In [51]:
number2 = int(input('Enter second integer: '))
number2

42

In [52]:
if number1 == number2:
      print(number1, 'is equal to', number2)

In [53]:
if number1 != number2:
      print(number1, 'is not equal to', number2)

37 is not equal to 42


In [54]:
if number1 < number2:
      print(number1, 'is less than', number2)

37 is less than 42


In [55]:
if number1 > number2:
      print(number1, 'is greater than', number2)

In [ ]:
if number1 <= number2:
      print(number1, 'is less than or equal to', number2)

In [58]:
if number1 >= number2:
      print(number1, 'is greater than or equal to', number2)

##Creating arrays from existing data

In [60]:
import numpy as np

numbers =np.array([2,3,5,7,11])
type(numbers)

numpy.ndarray

In [61]:
numbers

array([ 2,  3,  5,  7, 11])

*Multidimensional Arguments

In [63]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [66]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [69]:
np.arange(start=1,stop=6, step=1)

array([1, 2, 3, 4, 5])

In [71]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [72]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [73]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [74]:
numbers # numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

In [76]:
numbers+=10
numbers

array([21, 22, 23, 24, 25])

In [78]:
grades = np.array([[87,96,70], [100,87,90],
                   [94,77,90], [100,81,82]])
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [80]:
grades[0,1] # row 0, column 1

96

In [81]:
grades[1]

array([100,  87,  90])

In [82]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [83]:
grades[[1,3]]

array([[100,  87,  90],
       [100,  81,  82]])

In [84]:
grades[:,0]

array([ 87, 100,  94, 100])

In [85]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [86]:
grades[:, 0:2]

array([[ 87,  96],
       [100,  87],
       [ 94,  77],
       [100,  81]])